# Generated by Django 5.2.6 on 2025-10-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
